### ISSUE TITLE
Socket Server Local Implementation

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/socket-project#13]
We will implement a basic socket server that can print out "hi" so that we have a basic understanding of its functionality -- this relates to #3

**Comment by mmilutinovic1313** [comment]
Reeeaaally simple: https://socket.io/get-started/chat/

## Steps:
1. install node 
2. install socket
3. git clone example repo `git clone https://github.com/socketio/chat-example.git`
4. you have a working chat client that you can mess with!

**Comment by gab5014** [comment]
Once this is setup run `node index.js` to start the server and go to localhost:3000

**Comment by mmilutinovic1313** [comment]
`cd chat-example` to get into the chat example project and then run `node index.js`. If this doesn't work, please consult the "fixing node" documentation below. 

- https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-1-change-the-permission-to-npms-default-directory
- https://github.com/psudug/nittany-vagrant/wiki/Manually-installing-node-and-npm

**Comment by mmilutinovic1313** [comment]
Everyone is up and running today which is great!

**Comment by mmilutinovic1313** [comment]
I believe everyone has this working now, so this is great! We also have an example of socket working within polymer which matches the scope that @btopro wants in our pull request. We need to figure out how to pull usernames from elms and then we will have a great working prototype!
